"""add foreign key to Review

Revision ID: 14d5ac444aac
Revises: 49b413b6d270
Create Date: 2025-06-14 05:02:57.521781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d5ac444aac'
down_revision = '49b413b6d270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   def upgrade():
    with op.batch_alter_table('onboardings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_onboarding_employee_id', 'employees', ['employee_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
